# Generated by Django 5.0.2 on 2024-03-26 12:34

import django.core.validators
import suppliers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(max_length=18, null=True, unique=True, validators=[suppliers.models.validate_cnpj]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+55\\d{2}\\d{4,5}\\d{4}$')]),
        ),
    ]
