# Generated by Django 5.0.2 on 2024-03-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
    ]
