# Generated by Django 5.0.2 on 2024-03-31 00:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_remove_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
