# Generated by Django 5.0.2 on 2024-03-31 00:59

from django.db import migrations

def clear_supplier_table(apps, schema_editor):
    Supplier = apps.get_model('suppliers', 'Supplier')
    Supplier.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_supplier_uuid'),
    ]

    operations = [
    ]


