# Generated by Django 5.0.2 on 2024-03-31 23:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_auto_20240330_2159'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='uuid',
        ),
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Número de telefone no formato: '+999999999'. Até 15 dígitos.", regex='^\\+?\\d{10,15}$')]),
        ),
    ]
