# Generated by Django 5.0.2 on 2024-04-07 08:31

import datetime
import django.core.validators
import suppliers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_fornecedores'),
        ('suppliers', '0008_alter_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='brands',
            field=models.ManyToManyField(blank=True, to='products.brand', verbose_name='Marcas'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.category', verbose_name='Categorias'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='supplier',
            name='departments',
            field=models.ManyToManyField(related_name='suppliers', to='products.departamento'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Mínimo para Pedido'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='order_response_deadline',
            field=models.TimeField(blank=True, null=True, verbose_name='Prazo de Resposta para Pedidos'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='products.subcategory', verbose_name='Subcategorias'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(default=0, max_length=18, unique=True, validators=[suppliers.models.validate_cnpj]),
            preserve_default=False,
        ),
    ]
