# Generated by Django 5.0.2 on 2024-04-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_supplier_active_supplier_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
