# Generated by Django 5.0.2 on 2024-04-08 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_fornecedores'),
        ('suppliers', '0010_supplier_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, related_name='suppliers', to='products.departamento'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='minimum_order_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Mínimo para Pedido'),
        ),
    ]
