# Generated by Django 5.0.2 on 2024-04-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_alter_supplier_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='zip_code',
        ),
    ]
