# Generated by Django 5.0.2 on 2024-04-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_remove_supplier_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
    ]
