# Generated by Django 5.0.2 on 2024-04-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_fornecedores'),
        ('suppliers', '0014_supplier_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='brands',
            field=models.ManyToManyField(blank=True, to='products.brand', verbose_name='Marcas'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='products.departamento'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='products.subcategory', verbose_name='Subcategorias'),
        ),
    ]
