# Generated by Django 5.0.2 on 2024-04-11 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_alter_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='delivery_days',
            field=models.CharField(blank=True, choices=[('Domingo', 'Domingo'), ('Segunda', 'Segunda-feira'), ('Terça', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira'), ('Sábado', 'Sábado')], max_length=100, null=True, verbose_name='Dias de Entrega'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='holiday_cover_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Fornecedor de Férias'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='holiday_cover_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Fornecedor de Férias'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='holiday_cover_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Número de telefone no formato: '+999999999'. Até 15 dígitos.", regex='^\\+?\\d{10,15}$')], verbose_name='Telefone do Fornecedor de Férias'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
