# Generated by Django 5.0.2 on 2024-04-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0017_supplier_delivery_days_supplier_holiday_cover_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='delivery_days',
            field=models.TextField(blank=True, null=True, verbose_name='Dias de Entrega'),
        ),
    ]
