# Generated by Django 5.0.2 on 2024-04-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0019_supplier_delivery_time_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='delivery_time_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='flexibility_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='partnership_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='price_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='quality_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='reliability_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
