# Generated by Django 5.0.2 on 2024-04-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0021_alter_supplier_options_supplier_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='comments',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Comentários'),
        ),
    ]
