# Generated by Django 5.0.2 on 2024-06-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0022_alter_supplier_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='billing_deadline',
            field=models.CharField(choices=[('1-2', '1 a 2 dias úteis'), ('3-5', '3 a 5 dias úteis'), ('6-10', '6 a 10 dias úteis'), ('11-15', '11 a 15 dias úteis'), ('15+', 'Mais de 15 dias úteis'), ('negotiable', 'A combinar')], default='1-2', max_length=20, verbose_name='Prazo de Faturamento'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='specific_billing_deadline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prazo Específico de Faturamento'),
        ),
    ]
