# Generated by Django 5.0.2 on 2024-06-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0023_supplier_billing_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='delivery_days',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dias de Entrega'),
        ),
    ]
