# Generated by Django 5.0.2 on 2024-03-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={'ordering': ['-data_abertura'], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nome'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='itemcotacao',
            options={'ordering': ['produto__name'], 'verbose_name': 'Item de Cotação', 'verbose_name_plural': 'Itens de Cotação'},
        ),
        migrations.AddField(
            model_name='itemcotacao',
            name='tipo_volume',
            field=models.CharField(choices=[('kg', 'Quilo'), ('un', 'Unidade'), ('cx', 'Caixa'), ('dp', 'Display'), ('fd', 'Fardo')], default='un', max_length=2),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='itemcotacao',
            unique_together={('cotacao', 'produto', 'tipo_volume')},
        ),
    ]
