# Generated by Django 5.0.2 on 2024-03-30 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0004_respostacotacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaItemCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_7_dias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_14_dias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_21_dias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_28_dias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.cotacao')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='cotacao.itemcotacao')),
            ],
        ),
    ]
