# Generated by Django 5.0.2 on 2024-03-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0005_respostaitemcotacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostaitemcotacao',
            name='cotacao',
        ),
        migrations.RemoveField(
            model_name='respostaitemcotacao',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='respostaitemcotacao',
            name='item_cotacao',
        ),
        migrations.DeleteModel(
            name='RespostaCotacao',
        ),
        migrations.DeleteModel(
            name='RespostaItemCotacao',
        ),
    ]
