# Generated by Django 5.0.2 on 2024-03-30 02:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0006_remove_respostaitemcotacao_cotacao_and_more'),
        ('suppliers', '0002_supplier_cnpj_alter_supplier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='RespostaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='suppliers.supplier')),
                ('item_cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='cotacao.itemcotacao')),
            ],
            options={
                'unique_together': {('item_cotacao', 'fornecedor')},
            },
        ),
    ]
