# Generated by Django 5.0.2 on 2024-03-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0008_remove_cotacao_access_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RespostaFornecedor',
        ),
    ]
