# Generated by Django 5.0.2 on 2024-03-31 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0009_delete_respostafornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
