# Generated by Django 5.0.2 on 2024-04-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0010_cotacao_uuid'),
        ('suppliers', '0008_alter_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='fornecedores_convidados',
            field=models.ManyToManyField(related_name='cotacoes_convidadas', to='suppliers.supplier'),
        ),
    ]
