# Generated by Django 5.0.2 on 2024-04-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0011_cotacao_fornecedores_convidados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotacao',
            name='fornecedores_convidados',
        ),
    ]
