# Generated by Django 5.0.2 on 2024-04-03 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0012_remove_cotacao_fornecedores_convidados'),
        ('products', '0004_departamento_alter_category_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes', to='products.departamento'),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
