# Generated by Django 5.0.2 on 2024-04-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0013_alter_cotacao_departamento_delete_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotacao',
            name='tipo_volume',
            field=models.CharField(choices=[('Kg', 'Quilo'), ('L', 'Litro'), ('Dp', 'Display'), ('Un', 'Unidade'), ('Cx', 'Caixa'), ('Fd', 'Fardo'), ('Bd', 'Bandeija'), ('Pc', 'Pacote'), ('Sc', 'Sache'), ('Tp', 'Take Profit')], default='un', max_length=2),
        ),
    ]
