# Generated by Django 5.0.2 on 2024-04-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0014_alter_itemcotacao_tipo_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=10),
        ),
    ]
