# Generated by Django 5.0.2 on 2024-04-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0015_cotacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='prazo_aviso',
            field=models.IntegerField(choices=[(7, '7 dias'), (14, '14 dias'), (21, '21 dias'), (28, '28 dias')], default=7, help_text='Prazo para aviso antes do fechamento'),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
    ]
