# Generated by Django 5.0.2 on 2024-04-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0016_cotacao_prazo_aviso_alter_cotacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='prazo_aviso',
            field=models.IntegerField(choices=[(7, '7 dias'), (14, '14 dias'), (21, '21 dias'), (28, '28 dias')], default=7, help_text='Prazo para os produtos'),
        ),
    ]
