# Generated by Django 5.0.2 on 2024-04-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0017_alter_cotacao_prazo_aviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='inativo', max_length=10),
        ),
    ]
