# Generated by Django 5.0.2 on 2024-04-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0019_alter_cotacao_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={},
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='prazo_aviso',
            field=models.IntegerField(choices=[(7, '7 dias'), (14, '14 dias'), (21, '21 dias'), (28, '28 dias')], default=21, help_text='Prazo para os produtos'),
        ),
    ]
