# Generated by Django 5.0.2 on 2024-04-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0020_alter_cotacao_options_alter_cotacao_prazo_aviso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={'ordering': ['data_abertura'], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='prazo_aviso',
            field=models.IntegerField(choices=[(0, 'à vista'), (7, '7 dias'), (14, '14 dias'), (21, '21 dias'), (28, '28 dias')], default=21, help_text='Prazo para os produtos'),
        ),
    ]
