# Generated by Django 5.0.2 on 2024-04-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0022_alter_itemcotacao_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotacao',
            old_name='prazo_aviso',
            new_name='prazo',
        ),
    ]
