# Generated by Django 5.0.2 on 2024-04-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0023_rename_prazo_aviso_cotacao_prazo'),
        ('products', '0011_embalagem_espessura_embalagem_raio_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['departamento'], name='cotacao_cot_departa_9c36da_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['status'], name='cotacao_cot_status_a8aaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['data_abertura'], name='cotacao_cot_data_ab_3347b7_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcotacao',
            index=models.Index(fields=['produto'], name='cotacao_ite_produto_d2865c_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcotacao',
            index=models.Index(fields=['cotacao'], name='cotacao_ite_cotacao_1bb120_idx'),
        ),
    ]
