# Generated by Django 5.0.2 on 2024-04-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0024_cotacao_cotacao_cot_departa_9c36da_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade do produto', verbose_name='Quantidade'),
        ),
    ]
