# Generated by Django 5.0.2 on 2024-04-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0026_alter_itemcotacao_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotacao',
            name='observacao',
            field=models.TextField(blank=True, default='', help_text='Observações sobre o item', max_length=100, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='itemcotacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade do produto', verbose_name='Quantidade'),
        ),
    ]
