# Generated by Django 5.0.2 on 2024-04-18 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0027_alter_itemcotacao_observacao_and_more'),
        ('products', '0011_embalagem_espessura_embalagem_raio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='Subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='itemcotacao',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AddField(
            model_name='itemcotacao',
            name='Departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.departamento'),
        ),
        migrations.AddField(
            model_name='itemcotacao',
            name='Subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['Category'], name='cotacao_cot_Categor_6d0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['Subcategory'], name='cotacao_cot_Subcate_0e7d01_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcotacao',
            index=models.Index(fields=['Departamento'], name='cotacao_ite_Departa_97f34a_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcotacao',
            index=models.Index(fields=['Category'], name='cotacao_ite_Categor_adb238_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcotacao',
            index=models.Index(fields=['Subcategory'], name='cotacao_ite_Subcate_af5aa5_idx'),
        ),
    ]
