# Generated by Django 5.0.2 on 2024-04-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0028_cotacao_category_cotacao_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cotacao',
            name='cotacao_cot_Categor_6d0cdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='cotacao',
            name='cotacao_cot_Subcate_0e7d01_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemcotacao',
            name='cotacao_ite_Departa_97f34a_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemcotacao',
            name='cotacao_ite_Categor_adb238_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemcotacao',
            name='cotacao_ite_Subcate_af5aa5_idx',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='Subcategory',
        ),
        migrations.RemoveField(
            model_name='itemcotacao',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='itemcotacao',
            name='Departamento',
        ),
        migrations.RemoveField(
            model_name='itemcotacao',
            name='Subcategory',
        ),
    ]
