# Generated by Django 5.0.2 on 2024-04-22 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0030_cotacao_usuario_criador'),
        ('suppliers', '0022_alter_supplier_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.cotacao')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
    ]
