# Generated by Django 5.0.2 on 2024-04-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0031_respostacotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostacotacao',
            name='observacao',
            field=models.TextField(blank=True, default='', help_text='Observações sobre o item', max_length=100, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='respostacotacao',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço do produto', max_digits=10, null=True, verbose_name='Preço'),
        ),
    ]
