# Generated by Django 5.0.2 on 2024-04-22 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0032_alter_respostacotacao_observacao_and_more'),
        ('suppliers', '0022_alter_supplier_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostacotacao',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=10, null=True, verbose_name='Preço'),
        ),
        migrations.CreateModel(
            name='ItemRespostaCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(blank=True, decimal_places=3, help_text='Preço do produto', max_digits=10, null=True, verbose_name='Preço')),
                ('observacao', models.CharField(blank=True, max_length=100)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
                ('item_cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.itemcotacao')),
                ('resposta_cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.respostacotacao')),
            ],
        ),
    ]
