# Generated by Django 5.0.2 on 2024-04-29 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0033_alter_respostacotacao_preco_itemrespostacotacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostacotacao',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='respostacotacao',
            name='preco',
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.CharField(choices=[('ativo', 'Aberto'), ('inativo', 'Fechado')], default='ativo', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemrespostacotacao',
            name='resposta_cotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_respostas', to='cotacao.respostacotacao'),
        ),
    ]
