# Generated by Django 5.0.2 on 2024-04-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0034_remove_respostacotacao_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostacotacao',
            name='cotacao',
        ),
        migrations.RemoveField(
            model_name='respostacotacao',
            name='fornecedor',
        ),
        migrations.DeleteModel(
            name='ItemRespostaCotacao',
        ),
        migrations.DeleteModel(
            name='RespostaCotacao',
        ),
    ]
