# Generated by Django 5.0.2 on 2024-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0036_fornecedorcotacaotoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotacao',
            name='tipo_volume',
            field=models.CharField(choices=[('Kg', 'Quilo(s)'), ('L', 'Litro(s)'), ('Dp', 'Display(s)'), ('Un', 'Unidade(s)'), ('Cx', 'Caixa(s)'), ('Fd', 'Fardo(s)'), ('Bd', 'Bandeija(s)'), ('Pc', 'Pacote(s)'), ('Sc', 'Sache(s)'), ('Tp', 'Take Profit(s)')], default='un', help_text='Tipo de volume do produto', max_length=2, verbose_name='Tipo de Volume'),
        ),
    ]
