# Generated by Django 5.0.2 on 2024-04-29 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0035_remove_respostacotacao_cotacao_and_more'),
        ('respostas', '0001_initial'),
        ('suppliers', '0022_alter_supplier_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.cotacao')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'unique_together': {('cotacao', 'fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='ItemRespostaCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('item_cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.itemcotacao')),
                ('resposta_cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respostas.respostacotacao')),
            ],
            options={
                'unique_together': {('resposta_cotacao', 'item_cotacao')},
            },
        ),
        migrations.DeleteModel(
            name='RespostaFornecedor',
        ),
    ]
