# Generated by Django 5.0.2 on 2024-05-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0002_respostacotacao_itemrespostacotacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrespostacotacao',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
