# Generated by Django 5.0.2 on 2024-05-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0003_alter_itemrespostacotacao_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrespostacotacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='respostas/'),
        ),
    ]
