# Generated by Django 5.0.2 on 2024-05-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_embalagem_espessura_embalagem_raio_and_more'),
        ('respostas', '0004_itemrespostacotacao_imagem'),
        ('suppliers', '0022_alter_supplier_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('tipo_volume', models.CharField(choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=50, verbose_name='Tipo de Volume')),
                ('preco', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Preço')),
                ('data_requisicao', models.DateField(verbose_name='Data da Requisição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=50, verbose_name='Status do Pedido')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
