# Generated by Django 5.0.2 on 2024-05-08 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0006_remove_pedido_data_requisicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_agrupado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='respostas.pedidoagrupado', verbose_name='Pedido Agrupado'),
            preserve_default=False,
        ),
    ]
