# Generated by Django 5.0.2 on 2024-05-08 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0007_alter_pedido_pedido_agrupado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_agrupado',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='respostas.pedidoagrupado', verbose_name='Pedido Agrupado'),
        ),
    ]
