# Generated by Django 5.0.2 on 2024-05-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0008_alter_pedido_pedido_agrupado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrespostacotacao',
            name='prazo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrespostacotacao',
            name='prazo_alternativo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrespostacotacao',
            name='preco_prazo_alternativo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
