# Generated by Django 5.0.2 on 2024-05-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0009_itemrespostacotacao_prazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostacotacao',
            name='prazo_alternativo',
            field=models.CharField(blank=True, choices=[('avista', 'À vista'), ('7', '7 dias'), ('14', '14 dias'), ('21', '21 dias'), ('28', '28 dias')], max_length=20, null=True),
        ),
    ]
