# Generated by Django 5.0.2 on 2024-05-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0010_respostacotacao_prazo_alternativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostacotacao',
            name='prazo_alternativo',
            field=models.IntegerField(blank=True, choices=[(0, 'À vista'), (7, '7 dias'), (14, '14 dias'), (21, '21 dias'), (28, '28 dias')], null=True),
        ),
    ]
