# Generated by Django 5.0.2 on 2024-06-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0013_pedido_prazo_alternativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='prazo_alternativo',
        ),
    ]
