# Generated by Django 5.0.2 on 2024-06-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0015_pedido_prazo_alternativo_usado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='prazo_alternativo_usado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='prazo_alternativo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo Alternativo'),
        ),
    ]
