# Generated by Django 5.0.2 on 2024-06-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0016_remove_pedido_prazo_alternativo_usado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
