# Generated by Django 5.0.2 on 2024-03-15 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_abertura', models.DateField()),
                ('data_fechamento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VolumeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CotationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('preco_7_dias', models.DecimalField(decimal_places=3, max_digits=6)),
                ('preco_14_dias', models.DecimalField(decimal_places=3, max_digits=6)),
                ('preco_21_dias', models.DecimalField(decimal_places=3, max_digits=6)),
                ('preco_28_dias', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.cotation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('tipo_volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.volumetype')),
            ],
        ),
        migrations.AddField(
            model_name='cotation',
            name='produtos',
            field=models.ManyToManyField(through='quotations.CotationProduct', to='products.product'),
        ),
    ]
