# Generated by Django 5.0.2 on 2024-04-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_departamento_alter_category_department_and_more'),
        ('suppliers', '0008_alter_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_de_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AddField(
            model_name='product',
            name='descricao',
            field=models.TextField(blank=True, max_length=50, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='product',
            name='fornecedores',
            field=models.ManyToManyField(related_name='produtos', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='preco_de_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo'),
        ),
        migrations.AddField(
            model_name='product',
            name='unidade_de_medida',
            field=models.CharField(choices=[('Kg', 'Quilo'), ('L', 'Litro'), ('Dp', 'Display'), ('Un', 'Unidade'), ('Cx', 'Caixa'), ('Fd', 'Fardo'), ('Bdj', 'Bandeija'), ('Pct', 'Pacote'), ('Sch', 'Sache'), ('Tp', 'Take Profit')], max_length=50, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
