# Generated by Django 5.0.2 on 2024-04-07 04:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_data_de_validade_product_descricao_and_more'),
        ('suppliers', '0008_alter_supplier_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fornecedores',
            field=models.ManyToManyField(blank=True, null=True, related_name='produtos', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unidade_de_medida',
            field=models.CharField(blank=True, choices=[('Kg', 'Quilo'), ('L', 'Litro'), ('Dp', 'Display'), ('Un', 'Unidade'), ('Cx', 'Caixa'), ('Fd', 'Fardo'), ('Bdj', 'Bandeija'), ('Pct', 'Pacote'), ('Sch', 'Sache'), ('Tp', 'Take Profit')], max_length=50, null=True, verbose_name='Unidade de Medida'),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=13, null=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('descricao', models.TextField(blank=True, max_length=50, verbose_name='Descrição')),
                ('preco_de_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo')),
                ('unidade_de_medida', models.CharField(blank=True, choices=[('Kg', 'Quilo'), ('L', 'Litro'), ('Dp', 'Display'), ('Un', 'Unidade'), ('Cx', 'Caixa'), ('Fd', 'Fardo'), ('Bdj', 'Bandeija'), ('Pct', 'Pacote'), ('Sch', 'Sache'), ('Tp', 'Take Profit')], max_length=50, null=True, verbose_name='Unidade de Medida')),
                ('data_de_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('brand', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.brand')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.category')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.subcategory')),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data da Atualização')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
