# Generated by Django 5.0.2 on 2024-04-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_notas_product_sku_alter_product_fornecedores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fornecedores',
        ),
    ]
