# Generated by Django 5.0.2 on 2024-04-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productline_historicalproduct_product_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='altura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura da Embalagem'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='comprimento_embalagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comprimento da Embalagem'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='espessura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Espessura da Embalagem'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='largura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largura da Embalagem'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='unidade_altura',
            field=models.CharField(blank=True, choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=2, null=True, verbose_name='Unidade de Medida Altura'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='unidade_comprimento',
            field=models.CharField(blank=True, choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=2, null=True, verbose_name='Unidade de Medida Comprimento'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='unidade_espessura',
            field=models.CharField(blank=True, choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=2, null=True, verbose_name='Unidade de Medida Espessura'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='unidade_largura',
            field=models.CharField(blank=True, choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=2, null=True, verbose_name='Unidade de Medida Largura'),
        ),
        migrations.AddField(
            model_name='product',
            name='altura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura da Embalagem'),
        ),
        migrations.AddField(
            model_name='product',
            name='comprimento_embalagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comprimento da Embalagem'),
        ),
        migrations.AddField(
            model_name='product',
            name='espessura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Espessura da Embalagem'),
        ),
        migrations.AddField(
            model_name='product',
            name='largura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largura da Embalagem'),
        ),
        migrations.AddField(
            model_name='product',
            name='unidade_altura',
            field=models.CharField(blank=True, choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=2, null=True, verbose_name='Unidade de Medida Altura'),
        ),
        migrations.AddField(
            model_name='product',
            name='unidade_comprimento',
            field=models.CharField(blank=True, choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=2, null=True, verbose_name='Unidade de Medida Comprimento'),
        ),
        migrations.AddField(
            model_name='product',
            name='unidade_espessura',
            field=models.CharField(blank=True, choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=2, null=True, verbose_name='Unidade de Medida Espessura'),
        ),
        migrations.AddField(
            model_name='product',
            name='unidade_largura',
            field=models.CharField(blank=True, choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=2, null=True, verbose_name='Unidade de Medida Largura'),
        ),
    ]
