# Generated by Django 5.0.2 on 2024-04-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_embalagem_historicalproduct_altura_embalagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='altura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Altura da Embalagem'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='comprimento_embalagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Comprimento da Embalagem'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='espessura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Espessura da Embalagem'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='largura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Largura da Embalagem'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='preco_de_custo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Preço de Custo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='altura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Altura da Embalagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comprimento_embalagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Comprimento da Embalagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='espessura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Espessura da Embalagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='largura_embalagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Largura da Embalagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preco_de_custo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Preço de Custo'),
        ),
    ]
