# Generated by Django 5.0.2 on 2024-04-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_historicalproduct_altura_embalagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embalagem',
            name='espessura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='embalagem',
            name='raio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='raio_embalagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Raio da Embalagem'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='unidade_raio',
            field=models.CharField(blank=True, choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=2, null=True, verbose_name='Unidade de Medida Raio'),
        ),
        migrations.AddField(
            model_name='product',
            name='raio_embalagem',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Raio da Embalagem'),
        ),
        migrations.AddField(
            model_name='product',
            name='unidade_raio',
            field=models.CharField(blank=True, choices=[('mm', 'Milímetro'), ('cm', 'Centímetro'), ('m', 'Metro')], max_length=2, null=True, verbose_name='Unidade de Medida Raio'),
        ),
    ]
