# Generated by Django 5.0.2 on 2024-05-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productpricehistory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricehistory',
            name='date',
            field=models.DateField(verbose_name='Data da Atualização'),
        ),
    ]
