# Generated by Django 5.0.2 on 2024-05-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_historicalproduct_quantidade_por_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='unidade_de_medida',
            field=models.CharField(blank=True, choices=[('Kg', 'Quilo'), ('Dp', 'Display'), ('Un', 'Unidade'), ('Cx', 'Caixa'), ('Fd', 'Fardo'), ('Pct', 'Pacote'), ('Sch', 'Sache'), ('Tp', 'Take Profit')], max_length=50, null=True, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unidade_de_medida',
            field=models.CharField(blank=True, choices=[('Kg', 'Quilo'), ('Dp', 'Display'), ('Un', 'Unidade'), ('Cx', 'Caixa'), ('Fd', 'Fardo'), ('Pct', 'Pacote'), ('Sch', 'Sache'), ('Tp', 'Take Profit')], max_length=50, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
